name: CI
on: [push, pull_request]
env:
  MAKEFLAGS: -j3
  BUILD_NUMBER: ${{ github.run_number }}
jobs:
  fedora:
    name: Build on Fedora to ${{ matrix.container }}
    runs-on: ubuntu-latest
    container: ${{ matrix.container }}
    strategy:
      matrix:
        container: ['fedora:36']
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Install Deps
      run: dnf install -y cmake rpm-build
    - name: Build
      run: |
        cmake -B build -S .
        cmake --build build --target package
    - name: Archive artifacts
      uses: actions/upload-artifact@v3
      with:
        name: rpms
        path: build/*.rpm
  ubuntu:
    name: Build on Ubuntu
    runs-on: ubuntu-20.04
    env:
      DEBIAN_FRONTEND: noninteractive
      DEBFULLNAME: github-actions
      DEBEMAIL: github-actions@github.com
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Install dependencies
      run: sudo apt update -qq && sudo apt install --no-install-recommends -y dh-make dpkg-dev devscripts fakeroot cdbs
    - name: Build
      run: |
        cmake -B build -S .
        cmake --build build --target installer
        mv ../*.deb .
    - name: Archive artifacts
      uses: actions/upload-artifact@v3
      with:
        name: deb
        path: ./*.deb
  codeql:
    name: Run CodeQL tests
    if: github.repository == 'open-eid/firefox-pkcs11-loader'
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Install dependencies
      run: sudo apt update -qq && sudo apt install --no-install-recommends -y dh-make dpkg-dev devscripts fakeroot cdbs
    - name: Initialize CodeQL
      uses: github/codeql-action/init@v2
      with:
        languages: javascript
    - name: Autobuild
      uses: github/codeql-action/autobuild@v2
    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v2
