name: CI
on: [push, pull_request]
env:
  MAKEFLAGS: -j3
  BUILD_NUMBER: ${{ github.run_number }}
jobs:
  macos:
    name: Build on macOS
    runs-on: macos-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Build
      run: |
        cmake -B build -S .
        cmake --build build --target installer
    - name: Archive artifacts
      uses: actions/upload-artifact@v3
      with:
        name: pkg
        path: build/*.pkg
  fedora:
    name: Build on Fedora to ${{ matrix.container }}
    runs-on: ubuntu-latest
    container: ${{ matrix.container }}
    strategy:
      matrix:
        container: ['fedora:36']
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Install Deps
      run: dnf install -y cmake rpm-build
    - name: Build
      run: |
        cmake -B build -S .
        cmake --build build --target package
    - name: Archive artifacts
      uses: actions/upload-artifact@v3
      with:
        name: rpms
        path: build/*.rpm
  ubuntu:
    name: Build on Ubuntu
    runs-on: ubuntu-latest
    env:
      DEBIAN_FRONTEND: noninteractive
      DEBFULLNAME: github-actions
      DEBEMAIL: github-actions@github.com
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Install dependencies
      run: sudo apt-get update -qq && sudo apt-get install --no-install-recommends -y dh-make dpkg-dev devscripts fakeroot cdbs
    - name: Build
      run: |
        cmake -B build -S .
        cmake --build build --target installer
        mv ../*.deb .
    - name: Archive artifacts
      uses: actions/upload-artifact@v3
      with:
        name: deb
        path: ./*.deb
  windows:
    name: Build on Windows
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Build
      run: |
        cmake -B build -S .
        cmake --build build --target installer
    - name: Archive artifacts
      uses: actions/upload-artifact@v3
      with:
        name: msi
        path: build/*.msi